# Breast Cancer Prediction using Support Vector Machine

## Importing Libraries and Dataset

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# importing the dataset
dataset = pd.read_csv('breast_cancer_data.csv')
dataset.head(10)

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN
5    843786         M  ...                  0.12440          NaN
6    844359         M  ...                  0.08368          NaN
7  84458202         M  ...                  0.11510          NaN
8    844981         M  ...                  0.10720          NaN
9  84501001         M  ...                  0.20750          NaN

[10 rows x 33 columns]

In [3]:
# dropping ineffective columns
dataset = dataset.drop(['id', 'Unnamed: 32'], axis=1)
dataset.shape

(569, 31)

## Processing the data
*   Checking for missing values
*   Splitting into independent features and dependent variable
*   Encoding categorical data



In [4]:
# Checking for missing values
dataset.isnull().values.any()

False

In [0]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

In [6]:
# checking number of features and amount of data
print('X.shape :', X.shape)
X[:5]

X.shape : (569, 30)


array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [0]:
# Encoding dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
y[:50]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0])

## Splitting into training and test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
X_train[:5]

array([[1.005e+01, 1.753e+01, 6.441e+01, 3.108e+02, 1.007e-01, 7.326e-02,
        2.511e-02, 1.775e-02, 1.890e-01, 6.331e-02, 2.619e-01, 2.015e+00,
        1.778e+00, 1.685e+01, 7.803e-03, 1.449e-02, 1.690e-02, 8.043e-03,
        2.100e-02, 2.778e-03, 1.116e+01, 2.684e+01, 7.198e+01, 3.840e+02,
        1.402e-01, 1.402e-01, 1.055e-01, 6.499e-02, 2.894e-01, 7.664e-02],
       [1.080e+01, 2.198e+01, 6.879e+01, 3.599e+02, 8.801e-02, 5.743e-02,
        3.614e-02, 1.404e-02, 2.016e-01, 5.977e-02, 3.077e-01, 1.621e+00,
        2.240e+00, 2.020e+01, 6.543e-03, 2.148e-02, 2.991e-02, 1.045e-02,
        1.844e-02, 2.690e-03, 1.276e+01, 3.204e+01, 8.369e+01, 4.895e+02,
        1.303e-01, 1.696e-01, 1.927e-01, 7.485e-02, 2.965e-01, 7.662e-02],
       [1.614e+01, 1.486e+01, 1.043e+02, 8.000e+02, 9.495e-02, 8.501e-02,
        5.500e-02, 4.528e-02, 1.735e-01, 5.875e-02, 2.387e-01, 6.372e-01,
        1.729e+00, 2.183e+01, 3.958e-03, 1.246e-02, 1.831e-02, 8.747e-03,
        1.500e-02, 1.621e-03, 1.771e

In [11]:
y_train[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

## Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train[:5]

array([[-1.15036482, -0.39064196, -1.12855021, -0.95876358,  0.3109837 ,
        -0.5959945 , -0.80259612, -0.80249002,  0.29453906,  0.0942515 ,
        -0.4950523 ,  1.48720153, -0.51448782, -0.49154005,  0.28149837,
        -0.60451206, -0.46900701, -0.61170002,  0.05798237, -0.35763702,
        -1.0431756 ,  0.21353282, -1.0360446 , -0.84880771,  0.34249851,
        -0.73009743, -0.81232053, -0.75798367, -0.01614761, -0.38503402],
       [-0.93798972,  0.68051405, -0.94820146, -0.82152548, -0.60963604,
        -0.90986721, -0.66066905, -0.89871612,  0.75493453, -0.42547082,
        -0.33381757,  0.75941203, -0.28751805, -0.42127695, -0.1620797 ,
        -0.20486693, -0.05029632, -0.20309076, -0.25469005, -0.39139463,
        -0.71565415,  1.06684183, -0.68992205, -0.66869703, -0.09553745,
        -0.53786647, -0.37504806, -0.60687023,  0.09669004, -0.38615797],
       [ 0.574121  , -1.03333557,  0.51394098,  0.40858627, -0.10616078,
        -0.36301886, -0.41799048, -0.08844569, -0

## Feature Selection

In [14]:
import statsmodels.api as sm

# Adding constant column of ones, mandatory for sm.OLS model
X_1 = sm.add_constant(X)
model = sm.OLS(y,X_1).fit()

# array of pvalues of all features
col_val = model.pvalues

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [15]:
# array of feature names
col_name = np.array(dataset.drop(['diagnosis'], axis=1).columns)
col_name = np.concatenate(([['const']], col_name.reshape(len(col_name), 1)))

# displaying feature names vs its pvalue
col_name_val = np.concatenate((col_name, col_val.reshape(len(col_val), 1)), axis = 1)
col_name_val

array([['const', 2.9581492378923364e-06],
       ['radius_mean', 0.20998515087273245],
       ['texture_mean', 0.567426382361138],
       ['perimeter_mean', 0.3446407831278586],
       ['area_mean', 0.5453913936113519],
       ['smoothness_mean', 0.966528678512118],
       ['compactness_mean', 0.0016346863367958221],
       ['concavity_mean', 0.18188720435566977],
       ['concave points_mean', 0.27965690529625015],
       ['symmetry_mean', 0.8900673024379991],
       ['fractal_dimension_mean', 0.9952395628706676],
       ['radius_se', 0.16180021314882054],
       ['texture_se', 0.8545254348216403],
       ['perimeter_se', 0.5841286130633738],
       ['area_se', 0.5092349481098869],
       ['smoothness_se', 0.017046174658361144],
       ['compactness_se', 0.9761447134692851],
       ['concavity_se', 0.006327374134565553],
       ['concave points_se', 0.05310331187514704],
       ['symmetry_se', 0.5340191409185916],
       ['fractal_dimension_se', 0.5407692671778805],
       ['radius_wo

In [16]:
# filtering features with pvalue less than 0.05
index = list(i for i in range(0, len(col_name_val)) if col_name_val[i][1]<=0.05)
print(col_name_val[index])

[['const' 2.9581492378923364e-06]
 ['compactness_mean' 0.0016346863367958221]
 ['smoothness_se' 0.017046174658361144]
 ['concavity_se' 0.006327374134565553]
 ['radius_worst' 0.0008139505462869231]
 ['area_worst' 0.0016475512605358567]]


In [17]:
# retrieving index numbers of the selected features
cols_index = list(i-1 for i in range(1, len(col_name_val)) if col_name_val[i][1]<=0.05)
print('number of selected features :', len(cols_index))
cols_index

number of selected features : 5


[5, 14, 16, 20, 23]

In [18]:
# checking data with training set
X_train[:10, cols_index]

array([[-0.5959945 ,  0.28149837, -0.46900701, -1.0431756 , -0.84880771],
       [-0.90986721, -0.1620797 , -0.05029632, -0.71565415, -0.66869703],
       [-0.36301886, -1.07211882, -0.42362791,  0.29761532,  0.11388819],
       [-0.64933105, -0.55285085, -0.64891421, -0.70132509, -0.65896593],
       [-1.0175317 , -0.67149038, -0.71006335, -0.42702588, -0.44095517],
       [-0.34834635, -0.9619284 , -0.10275585, -0.41269682, -0.4395894 ],
       [-1.18805004,  0.36282102, -0.52565042, -0.60306866, -0.59323833],
       [-0.52897683, -0.06843544, -0.58519037, -0.52118829, -0.52375487],
       [ 2.73585456,  0.34029007,  2.7397136 , -0.10564546, -0.20279933],
       [ 0.1542862 , -0.12969146, -0.33673176, -0.69927808, -0.69157364]])

In [0]:
# modifying training and test set with selected
X_train = X_train[:, cols_index]
X_test = X_test[:, cols_index]

## Training, Prediction and Results

### rbf kernel

In [20]:
# training
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'rbf', random_state = 0)
classifier1.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [0]:
# prediction
y_pred1 = classifier1.predict(X_test)

In [22]:
# results
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred1))
accuracy_score(y_test, y_pred1)

[[63  4]
 [ 4 43]]


0.9298245614035088

Note : The rbf kernel shows exceptional results of approximately 93% accuracy score. (For comparision, rbf kernel without feature selection shows 98% accuracy score)

### Linear Kernel

In [23]:
# training
classifier2 = SVC(kernel = 'linear', random_state = 0)
classifier2.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [0]:
# prediction
y_pred2 = classifier2.predict(X_test)

In [25]:
# results
print(confusion_matrix(y_test, y_pred2))
accuracy_score(y_test, y_pred2)

[[64  3]
 [ 3 44]]


0.9473684210526315

Note : The linear kernel shows exceptional results of approximately 95% accuracy score. (For comparision, linear kernel without feature selection shows 98% accuracy score)

## Conclusion
*   Feature selection was effectively done, the results obtained from selected 5 features, were significantly close to results using all the 30 features (for linear and rbf kernels).
*   The 'breast cancer prediction' model using 'support vector machine' was a success with approximately 95% accuracy obtained with the linear kernel.